### ISSUE TITLE
Cannot get vagrant file for kubernetes working on Windows

### ISSUE THREAD

**Issue by ssouris** [fabric8io/fabric8-installer#103]
Hi,

I am trying to use vagrant to setup a kubernetes cluster and when I do 'vagrant up'
I get the following error. 

I am using Windows 8 and Vagrant 1.8.5

`....\fabric8-installer\vagrant\kubernetes>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos-7.1' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'centos-7.1' (v0) for provider: virtualbox
    default: Downloading: centos-7.1
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/..../fabric8-installer/vagrant/kubernetes/centos-7.1`

Could you please give me any poiters?

Thanks in advance

**Comment by jimmidyson** [comment]
Sorry! I broke it :( Try to pull the latest changes & try again.

**Comment by ssouris** [comment]
Hey cool thanks I kind of figured it out that the image name was wrong. 
The thing is though, that vagrant could not ssh to the vm, so I tried using password ssh authentication by adding
`config.ssh.password = "vagrant"`
`config.ssh.paranoid = false`
to the Vagrant script and it worked :p.

But then I had problem with start-kubenertes script.
It needed a `sh /usr/bin/start-kubernetes` at the beginning instead of raw `/usr/bin/start-kubernetes`.
And then I bumped into the problem that sh was finding `\r` characters :/ maybe due to windows line ending chars.

Now the script is stuck in the until loop of the script :p 

Anyway thanks for fast response.

**Comment by jimmidyson** [comment]
IIRC there's a known problem in Vagrant 1.8.5 & the ssh private key it sets. Need to upgrade or downgrade to 1.8.4

**Comment by ssouris** [comment]
Hi,

indeed I downgraded my Vagrant to 1.8.4 and the ssh key problem went away.
Then I saved the `start-kubernetes`, `restart-kubernete` script with Unix line ending(so that they can work inside centos).
Next in the script `start-kubernetes` the docker parameter 
`--volume=/var/lib/kubelet/:/var/lib/kubelet:rw,shared`, 
and especially the `shared` part does not parse well. 
The centos vm is running docker 1.9.1. So I removed that just to see where I would be headed to.

Then I got a warning about IPv4 disabled and networking won't work (coming from docker daemon?)
see log
`==> default: Status: Downloaded newer image for gcr.io/google_containers/hyperkube-amd64:v1.3.4`
`==> default: WARNING: IPv4 forwarding is disabled. Networking will not work.`
`==> default: 96a88dbfff243c7fa4b799488c370222c0b9e060498a5f3371e6f3190ddaf607`
`==> default: cluster "default" set.`
`==> default: context "default" set.`
`==> default: switched to context "default".`

And although `docker ps` in the vm shows that there are a bunch of docker images up and running the are not exposed through the network.

Following the script logic `kubectl get pods` never returns anything and the script stays forever in the loop.

I am very close  :)

**Comment by BeerOpsHQ** [comment]
The SSH key prob is because of a missing line in a vagrant script to chmod 0600 /etc/authorized_key from memory. Works fine after that. - https://github.com/mitchellh/vagrant/issues/7667

I've tried exactly your approach about tonight as well...and got the same point.

Looking forward to the next installment of fun n games once someone gets to the bottom of that one :)
