### ISSUE TITLE
Cannot see details of a running Camel pod from Vagrant 

### ISSUE THREAD

**Issue by jdcockrill** [fabric8io/fabric8-installer#20]
I installed fabric8 using the instructions here: http://fabric8.io/guide/getStarted/vagrant.html. The only issue I had was that the dnsmasq configuration doesn't work. I am running Linux Mint 17.2 (Ubuntu-derivative) and it looks like there are some conflicts between dnsmasq and Network Manager. I got it working in the end by adding all the hostnames to my /etc/hosts file. I've also had to dial-back the resources to 1 CPU and 1024MB memory.

I then ran the quickstart-camel-servlet, following the instructions here: http://fabric8.io/guide/getStarted/example.html

I can see the App created in fabric8 and the example works fine. I can run the example itself, however if I go to the running pod and click on the 'Connect' button, I am presented with a screen, such as that below:

![screenshot from 2015-08-28 10 55 31](https://cloud.githubusercontent.com/assets/1013959/9543765/5f7faa06-4d73-11e5-91d4-7e6f4b43a8a8.png)

I was expecting to see something a bit like what you see at 21:35 in the following example video https://vimeo.com/album/2635012/video/130614784

The following is the output of the web console from Firefox:

| Message | File:Line |
| --- | --- |
| `mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create` | libs-375df221.js:60:13075 |
| `Tasks:  Array [  ]` | libs-375df221.js:88:3867 |
| `[api-manager] Loaded the config.js config!` | libs-375df221.js:11:25964 |
| `[hawtio-oauth] All oauth plugins have executed` | libs-375df221.js:11:25964 |
| `"[kubernetes-watcher] About to query root paths: https://vagrant.f8:8443/"` | libs-375df221.js:11:25964 |
| `[kubernetes-watcher] isOpenShift true with paths /api,/api/v1beta3,/api/v1,/controllers,/healthz,/healthz/ping,/logs/,/metrics,/ready,/osapi,/osapi/v1beta3,/oapi,/oapi/v1,/swaggerapi/` | libs-375df221.js:11:25964 |
| `[kubernetes-watcher] error :  Forbidden` | libs-375df221.js:11:25964 |

That last log message is associated with the following request:

```
GET /api/v1/namespaces HTTP/1.1
Host: vagrant.f8:8443
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://fabric8.vagrant.f8/?con=quickstart-war-camel-servlet-g9h96
Origin: http://fabric8.vagrant.f8
Connection: keep-alive
```

And the response headers are:

```
HTTP/1.1 403 Forbidden
access-control-allow-credentials: true
Access-Control-Allow-Headers: Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, X-Requested-With, If-Modified-Since
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin: http://fabric8.vagrant.f8
Cache-Control: no-store
Content-Type: application/json
Date: Fri, 28 Aug 2015 10:58:18 GMT
Content-Length: 254
```

Response content:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot list all namespaces in the cluster",
  "reason": "Forbidden",
  "details": {
    "kind": "namespaces"
  },
  "code": 403
}
```

The URL in the browser window in the screenshot is:
http://fabric8.vagrant.f8/?jolokiaUrl=https%3A%2F%2Fvagrant.f8%3A8443%2Fapi%2Fv1%2Fproxy%2Fnamespaces%2Fdefault%2Fpods%2Fquickstart-war-camel-servlet-g9h96%3A8778%2Fjolokia%2F&title=quickstart-war-camel-servlet-g9h96&returnTo=http%3A%2F%2Ffabric8.vagrant.f8%2Fkubernetes%2Fnamespace%2Fdefault%2Fpods%2Fquickstart-war-camel-servlet-g9h96#AD_v-zmZj2V3yRnNQrz2ClYu8oGTuzBpHyb9eff-BNs

**Comment by jdcockrill** [comment]
I discussed the issue with @jimmidyson on IRC and he asked me to raise the issue on github.

**Comment by davsclaus** [comment]
Have you tried with latest release. We have since upgraded to kubernetes v1 and things works better.

**Comment by davsclaus** [comment]
We need a new release of openshift to allow secured jolokia access. So when OS3 1.0.7 is out this is intended to work again.

**Comment by davsclaus** [comment]
The connect should work again with all latest releases - though the spring-boot quickstarts currently do not - its a known issue due the docker base image. @rhuss will fix this later as we are busy with a RH release.
