### ISSUE TITLE
On page http://fabric8.io/guide/getStarted/vagrant.html, link to download fabric8 templates 2.2.33 distribution doesn't work

### ISSUE THREAD

**Issue by alberttwong** [fabric8io/fabric8-installer#23]
On page http://fabric8.io/guide/getStarted/vagrant.html, link to download fabric8 templates 2.2.33 distribution doesn't work.  File not found.

**Comment by alberttwong** [comment]
Not sure if it's related but the icons from fabric8 templates (used template 2.2.23.1 instead) are also broken in the web UI.

**Comment by rawlingsj** [comment]
Ah we've broken down a few of the repositories recently and the versions between fabric8, ipaas-quickstarts, fabric-devops and fabric8-ipaas have become misaligned in the last one or two releases. Let me take a look.

**Comment by rawlingsj** [comment]
@alberttwong thanks for pointing this out.  2.2.34 has just been released, docs updated and that link now works http://fabric8.io/guide/getStarted/vagrant.html

**Comment by alberttwong** [comment]
Is there an easy way to find how which are the old templates and delete them and/or how to reset the image back to base and then re-add the 2.2.34 temples?

**Comment by christian-posta** [comment]
on vagrant you can just destroy it with `vagrant destroy` and then bring it
back up with `vagrant up`
on an installation of kube/openshift not on vagrant, it'd be nice to be
able to uninstall or nicely upgrade templates.
wonder if gofabric8 client can do that?
otherwise, if you do oc delete all -l 'component=fabric8' it deletes
everything and then you can add back the console, etc/

On Wed, Sep 23, 2015 at 3:05 PM, Albert Wong notifications@github.com
wrote:

> Is there an easy way to find how which are the old templates and delete
> them and/or how to reset the image back to base and then re-add the 2.2.34
> temples?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fabric8io/fabric8-installer/issues/23#issuecomment-142744731
> .

## 

_Christian Posta_
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by rawlingsj** [comment]
yeah there's an open issue to add this into the gofabric8 installer, until then if you have the cd-pipeline template running then I've been using the little script thats also on the issue..
https://github.com/fabric8io/fabric8/issues/4654

**Comment by jstrachan** [comment]
one option is to create everything in a namespace; then trash the whole namespace.

```
oc new-project cheese
oc project cheese
gofabric8 deploy -y
gofabric8 secrets -y
....
// now to trash it
oc delete project cheese
```

**Comment by rawlingsj** [comment]
yeah that's nice!

**Comment by alberttwong** [comment]
So what I did was use "vagrant destory -f".  It seems to redownload the images again which kinda sucks when you need to reset the demo but I know of no other way.  Asking http://serverfault.com/questions/724638/how-do-you-reset-vagrant-back-to-its-original-state to see if there are better answers. 

Is there a way to show the version of the kub templates?  After download the new vangrat git, I really don't know what is the version.   As a result, I don't know if I should just run "cd pipeline" or always install the new kub templates.  Any suggestions?
