### ISSUE TITLE
IllegalArgumentException No secret named: openshift-cert-secret

### ISSUE THREAD

**Issue by myfear** [fabric8io/fabric8-installer#27]
The fabric8-installer/cdelivery does not work. 
Maven install fails with the following exception.

Failed to create replicationController from kubernetes.json. java.lang.IllegalArgumentException: No secret named: openshift-cert-secrets for namespace default is available on Kubernetes at address https://172.28.128.4:8443. 

Any help appreciated.

**Comment by rawlingsj** [comment]
using the gofabric8 installer you can generate the secrets using...

`gofabric8 secrets`

**Comment by jimmidyson** [comment]
`openshift-cert-secrets` shouldn't be required any more should it?

**Comment by myfear** [comment]
@rawlingsj I'm actually running the vagrant box on windows. Do you have a tiny pointer for me, where to look at?

**Comment by jstrachan** [comment]
Ah - I wonder if we should sandbox lots of the fabric8-installer stuff; as the gofabric8 installer is working much better for us and is setting up the secrets etc.

e.g. if you start vagrant via this:
http://fabric8.io/guide/getStarted/vagrant.html

then the gofabric8 installer is used under the covers to install all the templates & setup all the secrets; then you can just run stuff via the Run... UI

**Comment by myfear** [comment]
@jstrachan Thank you. But this basically means, that I have no chance to run the cdelivery demo right now? Is there a way to manually execute the gofabric8 installer to generate the needed certificates in the vagrant box?

**Comment by jstrachan** [comment]
I've updated the fabric8-installer to move those old mvn based installers into the sandbox and to make the ReadMe point at the vagrant image & gofabric8 installer:
https://github.com/fabric8io/fabric8-installer

**Comment by jstrachan** [comment]
To run the cd pipeline demo:
- vagrant up via [these instructions and/or video](http://fabric8.io/guide/getStarted/vagrant.html)
- in the console click on the default workspace -> Runtime -> Run... 
- select the `cd-pipeline` template and run it

If you want to you can re-download all the docker images for the template first; so as soon as vagrant up finishes type

```
vagrant ssh
sudo bash
gofabric8 pull cd-pipeline
```

**Comment by jstrachan** [comment]
gonna close this one for now; we can reopen if you still have issues
