### ISSUE TITLE
dnsmasq configuration

### ISSUE THREAD

**Issue by petenorth** [fabric8io/fabric8-installer#30]
Hi,

I noticed that the vagrant openshift readme.md (as well as others) have

Add a line `server=/vagrant.dev/127.0.0.1#10053` to the `dnsmasq` configuration.

When I was running through the installs today I have a feeling that this line was being created dynamically? If not then the configuration that I have  that worked was

server=/vagrant.f8/127.0.0.1#10053

i.e. vagrant.f8 rather than vagrant.dev .

Peter (pfry)

**Comment by rhuss** [comment]
Thanks.

The readme is wrong indeed, must be `vagrant.f8`

**Comment by rhuss** [comment]
Sorry, can not find that reference anymore (it was fixed some time ago). Could you please point me to where you have seen this reference ? In this [readme](http://fabric8.io/guide/getStarted/vagrant.html) everything has been updated.

**Comment by petenorth** [comment]
https://github.com/fabric8io/fabric8-installer/tree/master/vagrant/openshift/ReadMe.md

https://github.com/fabric8io/fabric8-installer/blob/master/vagrant/kubernetes/ReadMe.md

**Comment by rhuss** [comment]
sorry, I looked into the wrong project ;-).
