### ISSUE TITLE
service not accessible after restart 

### ISSUE THREAD

**Issue by 0loky0** [fabric8io/fabric8-installer#8]
Hi ! 

Thanks for the excellent job done with fabric8 which is by the way awesome :) 
I have followed the tutorial to test in vagrant but with a local network perspective. 
I have replace all "172.28.128.4" to a valid ip local adress in vagrant and putted it to public : 

  config.vm.network "private_network", ip: "172.28.128.4"
  config.vm.network "public_network", ip: "192.168.0.240"

My VM is now in bridged mode and is pingable from another physical machine of the local network. 

http://fabric8.vagrant.f8/ is accessible by both machine.

But if I restart the VM 

> vagrant halt
> vagrant up

http://fabric8.vagrant.f8/ is in ERR_CONNECTION_REFUSED 
and 
http://192.168.0.240/ is in 503 Service Unavailable No server is available to handle this request.

Any idea ?

**Comment by jimmidyson** [comment]
Can you check your hosts file & make sure fabric8.vagrant.f8 is set to 192.168.0.240? Might just be some old values in there hopefully. I don't think anyone's tried the Vagrant box with a public IP like this but would be good to get this working.

**Comment by 0loky0** [comment]
Thanks @jimmidyson !

In fact port redirection are required in the card1 in the network settings of the VM. (the NAT)

I added : 
HOST        PORT     GUEST PORT 
127.0.0.1  80                        80  
127.0.0.1  8080                    8080 
127.0.0.1  8443                    8443
...

Strange things is that I was able to connect during the first execution consecutive of the generation ! 

By the way it works just fine 

I repeat but what an amazing tools, just fan.

JF

**Comment by jimmidyson** [comment]
Glad it's working!

And thanks for the great feedback!
