### ISSUE TITLE
[vagrant/openshift] s2i failure on fedora

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/fabric8-installer#92]
I found that building images from sources may fail on fedora for external git repositories because of this https://github.com/openshift/origin/issues/8446

Would it be safe to conditionally turn on natdnshostresolver1 according to the platoform ?

**Comment by jimmidyson** [comment]
Sounds good to me. Thanks!

**Comment by lburgazzoli** [comment]
PR #93 it works on linux, I do not know if it cause any issue on other OS

**Comment by jstrachan** [comment]
BTW I've recreated my VM since on OS X and its fine so lets mark this closed. Thanks!
