### ISSUE TITLE
Upgrade to kubernetes 1.3 GA

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-installer#96]

**Comment by davsclaus** [comment]
]  <+jstrachan> davsclaus I tried it - DNS is borked in our vagrant VM with anything since 1.3.0-beta1

**Comment by davsclaus** [comment]
So lets wait with the upgrade until the DNS is fixed/working

**Comment by premdass** [comment]
Hi,

I tried F8-vagrant-Kube install process and the it seems to be broken. Can somebpdy confirm whether it is working with Kube 13 (with/withour beta please) ??

**Comment by davsclaus** [comment]
@jimmidyson has upgraded, thanks
