### ISSUE TITLE
ssh timeout with vagrant 1.8.5

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/fabric8-installer#98]
I've upgraded vagrant to 1.8.5 as it supports VirtualBox 5.1 and I ran into the following issue:

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
```

Then the installation hangs as it is not able to ssh in the box and the issues seems related to vagrant replacing the default insecure ssh key by default so a workaround is to disable key replacement by:

```
config.ssh.insert_key = false
```

I will provide a PR if the workaround is acceptable.

**Comment by TrentBartlem** [comment]
Cause is https://github.com/mitchellh/vagrant/issues/7610

**Comment by davsclaus** [comment]
I think I heard that some OS3 users with the CDK had issues with Vagrant 1.8.5. But downgrading to 1.8.4 works.

**Comment by lburgazzoli** [comment]
Should have been fixed in latest vagrant releases
